[2019-08-26 17:01:41,031] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=673975434, epoch=INITIAL) to node 0: java.net.SocketTimeoutException: Failed to connect within 30000 ms. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:41,052] WARN Client session timed out, have not heard from server in 39491ms for sessionid 0x1000c46ec990004 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:41,055] INFO [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=1771423881, epoch=INITIAL) to node 2: java.net.SocketTimeoutException: Failed to connect within 30000 ms. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:41,052] INFO [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1243800853, epoch=INITIAL) to node 1: java.net.SocketTimeoutException: Failed to connect within 30000 ms. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:44,647] WARN [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={testKafka-1=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[59]), testKafka1-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), test-kafka-broker-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[46]), topic127-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic125-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic130-0=(fetchOffset=348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1771423881, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:103)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:44,644] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic128-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic123-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic130-2=(fetchOffset=225, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), Multibrokerapplication-0=(fetchOffset=5, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[67]), topic132-1=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[26]), topic131-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[26]), topic125-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka-2=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[62]), topic127-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[43]), topic129-0=(fetchOffset=117, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[30]), topic126-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=673975434, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:103)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:44,646] INFO Client session timed out, have not heard from server in 39491ms for sessionid 0x1000c46ec990004, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:41,032] WARN Client session timed out, have not heard from server in 39471ms for sessionid 0x1000c46ec990005 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:41,031] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=33562070, epoch=INITIAL) to node 1: java.net.SocketTimeoutException: Failed to connect within 30000 ms. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:44,648] WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic127-0=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), Multibrokerapplication-1=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[69]), topic128-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[33]), testKafka-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[63]), topic130-1=(fetchOffset=336, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic132-0=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[25]), topic131-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[25]), testKafka1-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic125-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1243800853, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:103)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:44,651] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic127-0=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), test-kafka-broker-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[56]), Multibrokerapplication-1=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[69]), testKafka1-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic130-1=(fetchOffset=336, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), testKafka-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[63]), testKafka1-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic125-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=33562070, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:103)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:44,650] INFO Client session timed out, have not heard from server in 39471ms for sessionid 0x1000c46ec990005, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:41,033] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1930008219, epoch=INITIAL) to node 0: java.net.SocketTimeoutException: Failed to connect within 30000 ms. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:41,033] WARN Client session timed out, have not heard from server in 40364ms for sessionid 0x1000c46ec990006 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:41,033] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=1705878705, epoch=INITIAL) to node 2: java.net.SocketTimeoutException: Failed to connect within 30000 ms. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:44,741] INFO Client session timed out, have not heard from server in 40364ms for sessionid 0x1000c46ec990006, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:44,741] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic130-2=(fetchOffset=225, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic125-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka-2=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[62]), topic127-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[43]), test-kafka-broker-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[55]), Multibrokerapplication-0=(fetchOffset=5, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[67])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1930008219, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:103)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:44,742] WARN [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={testKafka-1=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[59]), topic129-1=(fetchOffset=117, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[30]), testKafka1-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic131-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[27]), topic132-2=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[27]), topic127-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic126-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[34]), topic125-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic130-0=(fetchOffset=348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic124-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[34])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1705878705, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:103)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,499] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,632] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,713] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,658] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,751] WARN [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,661] WARN [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,661] WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,751] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,658] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,953] INFO [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1243800853, epoch=INITIAL) to node 1: java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:46,952] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=1705878705, epoch=INITIAL) to node 2: java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:46,952] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=33562070, epoch=INITIAL) to node 1: java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:46,952] INFO [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=1771423881, epoch=INITIAL) to node 2: java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:46,953] WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic127-0=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), Multibrokerapplication-1=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[69]), topic128-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[33]), testKafka-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[63]), topic130-1=(fetchOffset=336, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic132-0=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[25]), topic131-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[25]), testKafka1-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic125-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1243800853, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,953] WARN [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={testKafka-1=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[59]), topic129-1=(fetchOffset=117, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[30]), testKafka1-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic131-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[27]), topic132-2=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[27]), topic127-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic126-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[34]), topic125-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic130-0=(fetchOffset=348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic124-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[34])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1705878705, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,948] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,953] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic127-0=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), test-kafka-broker-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[56]), Multibrokerapplication-1=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[69]), testKafka1-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic130-1=(fetchOffset=336, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), testKafka-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[63]), testKafka1-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic125-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=33562070, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,948] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,948] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,953] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1930008219, epoch=INITIAL) to node 0: java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:46,953] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=673975434, epoch=INITIAL) to node 0: java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:46,953] WARN [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={testKafka-1=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[59]), testKafka1-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), test-kafka-broker-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[46]), topic127-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic125-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic130-0=(fetchOffset=348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1771423881, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,955] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic130-2=(fetchOffset=225, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic125-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka-2=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[62]), topic127-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[43]), test-kafka-broker-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[55]), Multibrokerapplication-0=(fetchOffset=5, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[67])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1930008219, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,956] WARN Unable to reconnect to ZooKeeper service, session 0x1000c46ec990004 has expired (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,956] INFO Unable to reconnect to ZooKeeper service, session 0x1000c46ec990004 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,955] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic128-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic123-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic130-2=(fetchOffset=225, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic126-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic132-1=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[26]), topic131-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[26]), topic125-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka-2=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[62]), topic127-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[43]), topic129-0=(fetchOffset=117, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[30]), Multibrokerapplication-0=(fetchOffset=5, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[67])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=673975434, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:46,956] INFO EventThread shut down for session: 0x1000c46ec990004 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,957] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2019-08-26 17:01:46,958] WARN Unable to reconnect to ZooKeeper service, session 0x1000c46ec990005 has expired (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,958] INFO Unable to reconnect to ZooKeeper service, session 0x1000c46ec990005 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,958] WARN Unable to reconnect to ZooKeeper service, session 0x1000c46ec990006 has expired (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,958] INFO Unable to reconnect to ZooKeeper service, session 0x1000c46ec990006 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,959] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2019-08-26 17:01:46,959] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7b4c50bc (org.apache.zookeeper.ZooKeeper)
[2019-08-26 17:01:46,958] INFO EventThread shut down for session: 0x1000c46ec990005 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,958] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2019-08-26 17:01:46,958] INFO EventThread shut down for session: 0x1000c46ec990006 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,961] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2019-08-26 17:01:46,959] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2019-08-26 17:01:46,961] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7b4c50bc (org.apache.zookeeper.ZooKeeper)
[2019-08-26 17:01:46,962] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,964] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2019-08-26 17:01:46,964] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,969] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:46,964] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7b4c50bc (org.apache.zookeeper.ZooKeeper)
[2019-08-26 17:01:46,967] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,976] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:46,972] INFO Creating /brokers/ids/2 (is it secure? false) (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:47,199] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:47,200] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:47,202] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x1000c46ec990007, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:47,211] INFO Creating /brokers/ids/1 (is it secure? false) (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:47,410] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x1000c46ec990008, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:47,518] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x1000c46ec990009, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2019-08-26 17:01:47,808] INFO Stat of the created znode at /brokers/ids/0 is: 10686,10686,1566819107205,1566819107205,1,0,0,72071092794621959,196,0,10686
 (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:47,809] INFO Registered broker 0 at path /brokers/ids/0 with addresses: ArrayBuffer(EndPoint(192.168.0.102,9092,ListenerName(PLAINTEXT),PLAINTEXT)), czxid (broker epoch): 10686 (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:47,809] INFO Stat of the created znode at /brokers/ids/2 is: 10687,10687,1566819107518,1566819107518,1,0,0,72071092794621960,196,0,10687
 (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:47,809] INFO Registered broker 2 at path /brokers/ids/2 with addresses: ArrayBuffer(EndPoint(192.168.0.102,9094,ListenerName(PLAINTEXT),PLAINTEXT)), czxid (broker epoch): 10687 (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:48,120] INFO Stat of the created znode at /brokers/ids/1 is: 10688,10688,1566819107519,1566819107519,1,0,0,72071092794621961,196,0,10688
 (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:48,262] INFO Registered broker 1 at path /brokers/ids/1 with addresses: ArrayBuffer(EndPoint(192.168.0.102,9093,ListenerName(PLAINTEXT),PLAINTEXT)), czxid (broker epoch): 10688 (kafka.zk.KafkaZkClient)
[2019-08-26 17:01:48,806] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,806] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,806] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,917] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,960] WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,960] WARN [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,139] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=1705878705, epoch=INITIAL) to node 2: java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:48,961] WARN [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,961] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,961] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,140] INFO [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=1771423881, epoch=INITIAL) to node 2: java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:49,139] INFO [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1243800853, epoch=INITIAL) to node 1: java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:49,140] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1930008219, epoch=INITIAL) to node 0: java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:49,140] WARN [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={testKafka-1=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[59]), testKafka1-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), test-kafka-broker-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[46]), topic127-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic125-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic130-0=(fetchOffset=348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1771423881, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,139] WARN [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={testKafka-1=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[59]), topic129-1=(fetchOffset=117, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[30]), testKafka1-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic131-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[27]), topic132-2=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[27]), topic127-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic126-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[34]), topic125-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic130-0=(fetchOffset=348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic124-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[34])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1705878705, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,960] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,140] WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic127-0=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), Multibrokerapplication-1=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[69]), topic128-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[33]), testKafka-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[63]), topic130-1=(fetchOffset=336, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic132-0=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[25]), topic131-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[25]), testKafka1-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic125-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1243800853, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,143] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=33562070, epoch=INITIAL) to node 1: java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:49,143] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic127-0=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), test-kafka-broker-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[56]), Multibrokerapplication-1=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[69]), testKafka1-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic130-1=(fetchOffset=336, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), testKafka-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[63]), testKafka1-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic125-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=33562070, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,141] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic130-2=(fetchOffset=225, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic125-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka-2=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[62]), topic127-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[43]), test-kafka-broker-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[55]), Multibrokerapplication-0=(fetchOffset=5, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[67])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1930008219, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,917] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:48,917] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,140] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=673975434, epoch=INITIAL) to node 0: java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:49,146] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic128-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic123-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic130-2=(fetchOffset=225, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), Multibrokerapplication-0=(fetchOffset=5, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[67]), topic132-1=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[26]), topic131-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[26]), topic125-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka-2=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[62]), topic127-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[43]), topic129-0=(fetchOffset=117, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[30]), topic126-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=673975434, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,331] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,331] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,331] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,580] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,580] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,580] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,681] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,682] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,682] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,788] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,788] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,788] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,894] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,895] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,894] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,996] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,996] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:49,996] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,100] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,101] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,100] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,204] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,204] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,208] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,306] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,306] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,314] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,412] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,413] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,416] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,516] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,516] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,521] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,618] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,618] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,626] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,720] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,720] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,732] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:50,903] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,052] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,058] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,058] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,147] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,147] WARN [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,147] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,230] INFO [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=33562070, epoch=INITIAL) to node 1: java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:51,230] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=1930008219, epoch=INITIAL) to node 0: java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:51,230] INFO [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=1771423881, epoch=INITIAL) to node 2: java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:51,162] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,230] WARN [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic130-2=(fetchOffset=225, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic125-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka-2=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[62]), topic127-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[43]), test-kafka-broker-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[55]), Multibrokerapplication-0=(fetchOffset=5, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[67])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1930008219, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,230] WARN [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={testKafka-1=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[59]), testKafka1-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), test-kafka-broker-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[46]), topic127-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic125-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic130-0=(fetchOffset=348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1771423881, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,160] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,158] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,147] WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,147] WARN [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,152] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,233] INFO [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error sending fetch request (sessionId=1243800853, epoch=INITIAL) to node 1: java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:51,233] INFO [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error sending fetch request (sessionId=1705878705, epoch=INITIAL) to node 2: java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:51,233] WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic127-0=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), Multibrokerapplication-1=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[69]), topic128-0=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[33]), testKafka-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[63]), topic130-1=(fetchOffset=336, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic132-0=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[25]), topic131-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[25]), testKafka1-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic125-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1243800853, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,233] WARN [ReplicaFetcher replicaId=1, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=1, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={testKafka-1=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[59]), topic129-1=(fetchOffset=117, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[30]), testKafka1-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic131-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[27]), topic132-2=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[27]), topic127-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic126-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[34]), topic125-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[40]), topic130-0=(fetchOffset=348, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic124-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[34])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=1705878705, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9094 (id: 2 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,231] WARN [ReplicaFetcher replicaId=2, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic127-0=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), test-kafka-broker-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[56]), Multibrokerapplication-1=(fetchOffset=3, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[69]), testKafka1-3=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic130-1=(fetchOffset=336, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), testKafka-0=(fetchOffset=4, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[63]), testKafka1-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), topic125-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=33562070, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9093 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,233] INFO [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error sending fetch request (sessionId=673975434, epoch=INITIAL) to node 0: java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.. (org.apache.kafka.clients.FetchSessionHandler)
[2019-08-26 17:01:51,234] WARN [ReplicaFetcher replicaId=2, leaderId=0, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=2, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={topic128-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic123-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic130-2=(fetchOffset=225, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[37]), topic126-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[35]), topic132-1=(fetchOffset=15, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[26]), topic131-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[26]), topic125-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka1-2=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[45]), testKafka-2=(fetchOffset=1, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[62]), topic127-1=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[43]), topic129-0=(fetchOffset=117, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[30]), Multibrokerapplication-0=(fetchOffset=5, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[67])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=673975434, epoch=INITIAL), rackId=) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 192.168.0.102:9092 (id: 0 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:102)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:197)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:286)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,335] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,335] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,335] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,443] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,443] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,443] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,545] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,545] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,545] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,651] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 192.168.0.102:9094 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,651] WARN [Controller id=2, targetBrokerId=1] Error connecting to node 192.168.0.102:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:01:51,651] WARN [Controller id=2, targetBrokerId=0] Error connecting to node 192.168.0.102:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2019-08-26 17:10:19,188] INFO [GroupMetadataManager brokerId=2] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-26 17:10:43,067] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-26 17:11:01,008] INFO [GroupMetadataManager brokerId=1] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-26 17:20:19,163] INFO [GroupMetadataManager brokerId=2] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-26 17:20:43,054] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-26 17:21:00,983] INFO [GroupMetadataManager brokerId=1] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-26 17:30:19,148] INFO [GroupMetadataManager brokerId=2] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-26 17:30:43,034] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-26 17:31:00,967] INFO [GroupMetadataManager brokerId=1] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
